apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-container
        image: 250063290522.dkr.ecr.ap-south-1.amazonaws.com/my-backend:latest
        ports:
        - containerPort: 5000 # Agar backend 5000 par chalta hai