apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-app # Ye deployment ke label se match hona chahiye
  ports:
    - protocol: TCP
      port: 80         # Cluster ke andar is port par access hoga
      targetPort: 5000 # Container ka port
  type: ClusterIP      # Sirf frontend se connect karne ke liye